apiVersion: v1
data:
  flink.streaming.conf: |
    env {
      execution.parallelism = 1
    }

    source {
      FakeSourceStream {
        result_table_name = "fake"
        field_name = "name,age"
      }
    }

    transform {
      sql {
        sql = "select name,age from fake"
      }
    }

    sink {
      ConsoleSink {}
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: seatunnel-config
