apiVersion: v1
kind: ConfigMap
metadata:
  name: xxx-unavailable
data:
  index.html: |
    <html>
    <body>
    <p>The service is unavailable, please try again later!</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx-unavailable
  labels:
    app: xxx-unavailable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx-unavailable
  template:
    metadata:
      labels:
        app: xxx-unavailable
    spec:
      enableServiceLinks: false
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: xxx-unavailable
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: xxx-unavailable
        configMap:
          name: xxx-unavailable

---
apiVersion: v1
kind: Service
metadata:
  name: xxx-unavailable
spec:
  selector:
    app: xxx-unavailable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxx-unavailable
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - xxx-unavailable.example.com
      secretName: deepwisdom-ai
  rules:
    - host: xxx-unavailable.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: xxx-unavailable
                port:
                  number: 80

