apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
    prometheus-operator-validated: "true"
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.25.0
    chart: kube-prometheus-stack-45.25.0
    heritage: Helm
    release: prometheus
  name: custom-minio-alert-rule
  namespace: prometheus
spec:
  groups:
    - name: MinIOAlerts
      rules:
        - alert: MinioClusterDiskOffline
          expr: minio_cluster_disk_offline_total > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Minio cluster disk offline (instance {{ $labels.instance }})
            description: |-
              Minio cluster disk is offline
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
        - alert: MinioNodeDiskOffline
          expr: minio_cluster_nodes_offline_total > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Minio node disk offline (instance {{ $labels.instance }})
            description: |-
              Minio cluster node disk is offline
                VALUE = {{ $value }}
                LABELS = {{ $labels }}
        - alert: MinioDiskSpaceUsage
          expr: disk_storage_available / disk_storage_total * 100 < 10
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Minio disk space usage (instance {{ $labels.instance }})
            description: |-
              Minio available free space is low (< 10%)
                VALUE = {{ $value }}
                LABELS = {{ $labels }}