apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.28
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysqld-config
              key: mysql_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        ## 覆盖 /etc/mysql/conf.d 目录进行挂载
        # - name: mysqld-config
        #   mountPath: "/etc/mysql/conf.d"
        #   readOnly: true
        # 不覆盖 /etc/mysql/conf.d 目录，挂载单个文件
        - name: mysqld-config
          mountPath: "/etc/mysql/conf.d/mysqld-custom.cnf"
          subPath: "mysqld-custom.cnf"
          readOnly: true
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqld-config
        configMap:
          name: mysqld-config
          items:
          - key: "mysqld-custom.cnf"
            path: "mysqld-custom.cnf"
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
