apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
    prometheus-operator-validated: "true"
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.25.0
    chart: kube-prometheus-stack-45.25.0
    heritage: Helm
    release: prometheus
  name: custom-mysql-alert-rule
  namespace: prometheus
spec:
  groups:
  - name: MySQLAlerts
    rules:
    - alert: MySQLDown
      expr: mysql_up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: MySQL down (instance {{ $labels.instance }})
        description: |-
          MySQL instance is down on {{ $labels.instance }}
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
    - alert: MySQLTooManyConnections(>80%)
      expr: max_over_time(mysql_global_status_threads_connected[1m]) /
        mysql_global_variables_max_connections * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL too many connections (> 80%) (instance {{ $labels.instance }})
        description: >-
          More than 80% of MySQL connections are in use on {{
          $labels.instance }}
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
    - alert: MySQLHighThreadsRunning
      expr: max_over_time(mysql_global_status_threads_running[1m]) /
        mysql_global_variables_max_connections * 100 > 60
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL high threads running (instance {{ $labels.instance }})
        description: >-
          More than 60% of MySQL connections are in running state on {{
          $labels.instance }}
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
    - alert: MySQLSlowQueries
      expr: increase(mysql_global_status_slow_queries[1m]) > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: MySQL slow queries (instance {{ $labels.instance }})
        description: |-
          MySQL server mysql has some new slow query.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
    - alert: MySQLRestarted
      expr: mysql_global_status_uptime < 60
      for: 0m
      labels:
        severity: info
      annotations:
        summary: MySQL restarted (instance {{ $labels.instance }})
        description: >-
          MySQL has just been restarted, less than one minute ago on {{
          $labels.instance }}.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}